version: '3.3'

services:
  selenium:
    image: selenium/standalone-chrome:3.141.59-xenon
    container_name: selenium-hub
    ports: 
      - 4444:4444
    volumes: 
      - /dev/shm:/dev/shm

  python:
    build: .
    depends_on: 
      - selenium
    container_name: 'beautiful_testing'
    tty: true
    ports: 
      - 9876:9876
    volumes:
      - ./result:/workdir/result
    environment:
      - 'TZ=Asia/Tokyo'